package lexer

type SemanticType = Tree

var table = map[string]map[string]Action {
	"\x19 :=  ● re \x18": {
		"LPAREN": {acType: "Shift", next: "group := LPAREN ● re RPAREN"},
		"WILDCARD": {acType: "Shift", next: "any := WILDCARD ● "},
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"LBRAC": {acType: "Shift", next: "posset := LBRAC ● setitems RBRAC"},
		"re": {acType: "Shift", next: "\x19 := re ● \x18"},
		"union": {acType: "Shift", next: "re := union ● "},
		"simplere": {acType: "Shift", next: "re := simplere ● "},
		"concat": {acType: "Shift", next: "simplere := concat ● "},
		"basicre": {acType: "Shift", next: "simplere := basicre ● "},
		"star": {acType: "Shift", next: "basicre := star ● "},
		"plus": {acType: "Shift", next: "basicre := plus ● "},
		"question": {acType: "Shift", next: "basicre := question ● "},
		"elemre": {acType: "Shift", next: "basicre := elemre ● "},
		"group": {acType: "Shift", next: "elemre := group ● "},
		"any": {acType: "Shift", next: "elemre := any ● "},
		"char": {acType: "Shift", next: "elemre := char ● "},
		"set": {acType: "Shift", next: "elemre := set ● "},
		"posset": {acType: "Shift", next: "set := posset ● "},
		"negset": {acType: "Shift", next: "set := negset ● "},
	},
	"\x19 := re ● \x18": {
		"ALTERNATE": {acType: "Shift", next: "union := re ALTERNATE ● simplere"},
		"\x18": {acType: "Accept"},
	},
	"union := re ALTERNATE ● simplere": {
		"LPAREN": {acType: "Shift", next: "group := LPAREN ● re RPAREN"},
		"WILDCARD": {acType: "Shift", next: "any := WILDCARD ● "},
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"LBRAC": {acType: "Shift", next: "posset := LBRAC ● setitems RBRAC"},
		"simplere": {acType: "Shift", next: "union := re ALTERNATE simplere ● "},
		"concat": {acType: "Shift", next: "simplere := concat ● "},
		"basicre": {acType: "Shift", next: "simplere := basicre ● "},
		"star": {acType: "Shift", next: "basicre := star ● "},
		"plus": {acType: "Shift", next: "basicre := plus ● "},
		"question": {acType: "Shift", next: "basicre := question ● "},
		"elemre": {acType: "Shift", next: "basicre := elemre ● "},
		"group": {acType: "Shift", next: "elemre := group ● "},
		"any": {acType: "Shift", next: "elemre := any ● "},
		"char": {acType: "Shift", next: "elemre := char ● "},
		"set": {acType: "Shift", next: "elemre := set ● "},
		"posset": {acType: "Shift", next: "set := posset ● "},
		"negset": {acType: "Shift", next: "set := negset ● "},
	},
	"union := re ALTERNATE simplere ● ": {
		"ALTERNATE": {acType: "Reduce", next: "union", reduceBy: 3},
		"LPAREN": {acType: "Shift", next: "group := LPAREN ● re RPAREN"},
		"RPAREN": {acType: "Reduce", next: "union", reduceBy: 3},
		"WILDCARD": {acType: "Shift", next: "any := WILDCARD ● "},
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"LBRAC": {acType: "Shift", next: "posset := LBRAC ● setitems RBRAC"},
		"\x18": {acType: "Reduce", next: "union", reduceBy: 3},
		"basicre": {acType: "Shift", next: "concat := simplere basicre ● "},
		"star": {acType: "Shift", next: "basicre := star ● "},
		"plus": {acType: "Shift", next: "basicre := plus ● "},
		"question": {acType: "Shift", next: "basicre := question ● "},
		"elemre": {acType: "Shift", next: "basicre := elemre ● "},
		"group": {acType: "Shift", next: "elemre := group ● "},
		"any": {acType: "Shift", next: "elemre := any ● "},
		"char": {acType: "Shift", next: "elemre := char ● "},
		"set": {acType: "Shift", next: "elemre := set ● "},
		"posset": {acType: "Shift", next: "set := posset ● "},
		"negset": {acType: "Shift", next: "set := negset ● "},
	},
	"concat := simplere basicre ● ": {
		"ALTERNATE": {acType: "Reduce", next: "concat", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "concat", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "concat", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "concat", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "concat", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "concat", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "concat", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "concat", reduceBy: 2},
		"N": {acType: "Reduce", next: "concat", reduceBy: 2},
		"T": {acType: "Reduce", next: "concat", reduceBy: 2},
		"R": {acType: "Reduce", next: "concat", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "concat", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "concat", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "concat", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "concat", reduceBy: 2},
	},
	"basicre := star ● ": {
		"ALTERNATE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"N": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"T": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"R": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "basicre", reduceBy: 1},
	},
	"basicre := plus ● ": {
		"ALTERNATE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"N": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"T": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"R": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "basicre", reduceBy: 1},
	},
	"basicre := question ● ": {
		"ALTERNATE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"N": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"T": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"R": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "basicre", reduceBy: 1},
	},
	"basicre := elemre ● ": {
		"ALTERNATE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"KLEENE": {acType: "Shift", next: "star := elemre KLEENE ● "},
		"PLUS": {acType: "Shift", next: "plus := elemre PLUS ● "},
		"QUESTION": {acType: "Shift", next: "question := elemre QUESTION ● "},
		"LPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"N": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"T": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"R": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "basicre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "basicre", reduceBy: 1},
	},
	"star := elemre KLEENE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "star", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "star", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "star", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "star", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "star", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "star", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "star", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "star", reduceBy: 2},
		"N": {acType: "Reduce", next: "star", reduceBy: 2},
		"T": {acType: "Reduce", next: "star", reduceBy: 2},
		"R": {acType: "Reduce", next: "star", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "star", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "star", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "star", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "star", reduceBy: 2},
	},
	"plus := elemre PLUS ● ": {
		"ALTERNATE": {acType: "Reduce", next: "plus", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "plus", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "plus", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "plus", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "plus", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "plus", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "plus", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "plus", reduceBy: 2},
		"N": {acType: "Reduce", next: "plus", reduceBy: 2},
		"T": {acType: "Reduce", next: "plus", reduceBy: 2},
		"R": {acType: "Reduce", next: "plus", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "plus", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "plus", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "plus", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "plus", reduceBy: 2},
	},
	"question := elemre QUESTION ● ": {
		"ALTERNATE": {acType: "Reduce", next: "question", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "question", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "question", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "question", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "question", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "question", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "question", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "question", reduceBy: 2},
		"N": {acType: "Reduce", next: "question", reduceBy: 2},
		"T": {acType: "Reduce", next: "question", reduceBy: 2},
		"R": {acType: "Reduce", next: "question", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "question", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "question", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "question", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "question", reduceBy: 2},
	},
	"elemre := group ● ": {
		"ALTERNATE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"N": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"T": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"R": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "elemre", reduceBy: 1},
	},
	"elemre := any ● ": {
		"ALTERNATE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"N": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"T": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"R": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "elemre", reduceBy: 1},
	},
	"elemre := char ● ": {
		"ALTERNATE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"N": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"T": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"R": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "elemre", reduceBy: 1},
	},
	"elemre := set ● ": {
		"ALTERNATE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"N": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"T": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"R": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "elemre", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "elemre", reduceBy: 1},
	},
	"set := posset ● ": {
		"ALTERNATE": {acType: "Reduce", next: "set", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "set", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "set", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "set", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "set", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "set", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "set", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "set", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "set", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "set", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "set", reduceBy: 1},
		"N": {acType: "Reduce", next: "set", reduceBy: 1},
		"T": {acType: "Reduce", next: "set", reduceBy: 1},
		"R": {acType: "Reduce", next: "set", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "set", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "set", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "set", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "set", reduceBy: 1},
	},
	"set := negset ● ": {
		"ALTERNATE": {acType: "Reduce", next: "set", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "set", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "set", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "set", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "set", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "set", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "set", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "set", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "set", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "set", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "set", reduceBy: 1},
		"N": {acType: "Reduce", next: "set", reduceBy: 1},
		"T": {acType: "Reduce", next: "set", reduceBy: 1},
		"R": {acType: "Reduce", next: "set", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "set", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "set", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "set", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "set", reduceBy: 1},
	},
	"group := LPAREN ● re RPAREN": {
		"LPAREN": {acType: "Shift", next: "group := LPAREN ● re RPAREN"},
		"WILDCARD": {acType: "Shift", next: "any := WILDCARD ● "},
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"LBRAC": {acType: "Shift", next: "posset := LBRAC ● setitems RBRAC"},
		"re": {acType: "Shift", next: "group := LPAREN re ● RPAREN"},
		"union": {acType: "Shift", next: "re := union ● "},
		"simplere": {acType: "Shift", next: "re := simplere ● "},
		"concat": {acType: "Shift", next: "simplere := concat ● "},
		"basicre": {acType: "Shift", next: "simplere := basicre ● "},
		"star": {acType: "Shift", next: "basicre := star ● "},
		"plus": {acType: "Shift", next: "basicre := plus ● "},
		"question": {acType: "Shift", next: "basicre := question ● "},
		"elemre": {acType: "Shift", next: "basicre := elemre ● "},
		"group": {acType: "Shift", next: "elemre := group ● "},
		"any": {acType: "Shift", next: "elemre := any ● "},
		"char": {acType: "Shift", next: "elemre := char ● "},
		"set": {acType: "Shift", next: "elemre := set ● "},
		"posset": {acType: "Shift", next: "set := posset ● "},
		"negset": {acType: "Shift", next: "set := negset ● "},
	},
	"group := LPAREN re ● RPAREN": {
		"ALTERNATE": {acType: "Shift", next: "union := re ALTERNATE ● simplere"},
		"RPAREN": {acType: "Shift", next: "group := LPAREN re RPAREN ● "},
	},
	"group := LPAREN re RPAREN ● ": {
		"ALTERNATE": {acType: "Reduce", next: "group", reduceBy: 3},
		"KLEENE": {acType: "Reduce", next: "group", reduceBy: 3},
		"PLUS": {acType: "Reduce", next: "group", reduceBy: 3},
		"QUESTION": {acType: "Reduce", next: "group", reduceBy: 3},
		"LPAREN": {acType: "Reduce", next: "group", reduceBy: 3},
		"RPAREN": {acType: "Reduce", next: "group", reduceBy: 3},
		"WILDCARD": {acType: "Reduce", next: "group", reduceBy: 3},
		"CHAR": {acType: "Reduce", next: "group", reduceBy: 3},
		"NEWLINE": {acType: "Reduce", next: "group", reduceBy: 3},
		"TAB": {acType: "Reduce", next: "group", reduceBy: 3},
		"RETURN": {acType: "Reduce", next: "group", reduceBy: 3},
		"N": {acType: "Reduce", next: "group", reduceBy: 3},
		"T": {acType: "Reduce", next: "group", reduceBy: 3},
		"R": {acType: "Reduce", next: "group", reduceBy: 3},
		"UNDERSCORE": {acType: "Reduce", next: "group", reduceBy: 3},
		"BSLASH": {acType: "Reduce", next: "group", reduceBy: 3},
		"LBRAC": {acType: "Reduce", next: "group", reduceBy: 3},
		"\x18": {acType: "Reduce", next: "group", reduceBy: 3},
	},
	"re := union ● ": {
		"ALTERNATE": {acType: "Reduce", next: "re", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "re", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "re", reduceBy: 1},
	},
	"re := simplere ● ": {
		"ALTERNATE": {acType: "Reduce", next: "re", reduceBy: 1},
		"LPAREN": {acType: "Shift", next: "group := LPAREN ● re RPAREN"},
		"RPAREN": {acType: "Reduce", next: "re", reduceBy: 1},
		"WILDCARD": {acType: "Shift", next: "any := WILDCARD ● "},
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"LBRAC": {acType: "Shift", next: "posset := LBRAC ● setitems RBRAC"},
		"\x18": {acType: "Reduce", next: "re", reduceBy: 1},
		"basicre": {acType: "Shift", next: "concat := simplere basicre ● "},
		"star": {acType: "Shift", next: "basicre := star ● "},
		"plus": {acType: "Shift", next: "basicre := plus ● "},
		"question": {acType: "Shift", next: "basicre := question ● "},
		"elemre": {acType: "Shift", next: "basicre := elemre ● "},
		"group": {acType: "Shift", next: "elemre := group ● "},
		"any": {acType: "Shift", next: "elemre := any ● "},
		"char": {acType: "Shift", next: "elemre := char ● "},
		"set": {acType: "Shift", next: "elemre := set ● "},
		"posset": {acType: "Shift", next: "set := posset ● "},
		"negset": {acType: "Shift", next: "set := negset ● "},
	},
	"any := WILDCARD ● ": {
		"ALTERNATE": {acType: "Reduce", next: "any", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "any", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "any", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "any", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "any", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "any", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "any", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "any", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "any", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "any", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "any", reduceBy: 1},
		"N": {acType: "Reduce", next: "any", reduceBy: 1},
		"T": {acType: "Reduce", next: "any", reduceBy: 1},
		"R": {acType: "Reduce", next: "any", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "any", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "any", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "any", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "any", reduceBy: 1},
	},
	"char := CHAR ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := NEWLINE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := TAB ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := RETURN ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := N ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := T ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := R ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := UNDERSCORE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 1},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 1},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 1},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 1},
		"N": {acType: "Reduce", next: "char", reduceBy: 1},
		"T": {acType: "Reduce", next: "char", reduceBy: 1},
		"R": {acType: "Reduce", next: "char", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 1},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 1},
	},
	"char := BSLASH ● LPAREN": {
		"ALTERNATE": {acType: "Shift", next: "char := BSLASH ALTERNATE ● "},
		"KLEENE": {acType: "Shift", next: "char := BSLASH KLEENE ● "},
		"PLUS": {acType: "Shift", next: "char := BSLASH PLUS ● "},
		"QUESTION": {acType: "Shift", next: "char := BSLASH QUESTION ● "},
		"LPAREN": {acType: "Shift", next: "char := BSLASH LPAREN ● "},
		"RPAREN": {acType: "Shift", next: "char := BSLASH RPAREN ● "},
		"WILDCARD": {acType: "Shift", next: "char := BSLASH WILDCARD ● "},
		"N": {acType: "Shift", next: "char := BSLASH N ● "},
		"T": {acType: "Shift", next: "char := BSLASH T ● "},
		"R": {acType: "Shift", next: "char := BSLASH R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := BSLASH UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH BSLASH ● "},
		"LBRAC": {acType: "Shift", next: "char := BSLASH LBRAC ● "},
		"RBRAC": {acType: "Shift", next: "char := BSLASH RBRAC ● "},
		"CARET": {acType: "Shift", next: "char := BSLASH CARET ● "},
		"HYPHEN": {acType: "Shift", next: "char := BSLASH HYPHEN ● "},
	},
	"char := BSLASH LPAREN ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH RPAREN ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH LBRAC ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH RBRAC ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH KLEENE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH PLUS ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH QUESTION ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH CARET ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH HYPHEN ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH WILDCARD ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH ALTERNATE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH BSLASH ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH UNDERSCORE ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH N ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH T ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"char := BSLASH R ● ": {
		"ALTERNATE": {acType: "Reduce", next: "char", reduceBy: 2},
		"KLEENE": {acType: "Reduce", next: "char", reduceBy: 2},
		"PLUS": {acType: "Reduce", next: "char", reduceBy: 2},
		"QUESTION": {acType: "Reduce", next: "char", reduceBy: 2},
		"LPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"RPAREN": {acType: "Reduce", next: "char", reduceBy: 2},
		"WILDCARD": {acType: "Reduce", next: "char", reduceBy: 2},
		"CHAR": {acType: "Reduce", next: "char", reduceBy: 2},
		"NEWLINE": {acType: "Reduce", next: "char", reduceBy: 2},
		"TAB": {acType: "Reduce", next: "char", reduceBy: 2},
		"RETURN": {acType: "Reduce", next: "char", reduceBy: 2},
		"N": {acType: "Reduce", next: "char", reduceBy: 2},
		"T": {acType: "Reduce", next: "char", reduceBy: 2},
		"R": {acType: "Reduce", next: "char", reduceBy: 2},
		"UNDERSCORE": {acType: "Reduce", next: "char", reduceBy: 2},
		"BSLASH": {acType: "Reduce", next: "char", reduceBy: 2},
		"LBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"RBRAC": {acType: "Reduce", next: "char", reduceBy: 2},
		"HYPHEN": {acType: "Reduce", next: "char", reduceBy: 2},
		"\x18": {acType: "Reduce", next: "char", reduceBy: 2},
	},
	"posset := LBRAC ● setitems RBRAC": {
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"CARET": {acType: "Shift", next: "negset := LBRAC CARET ● setitems RBRAC"},
		"char": {acType: "Shift", next: "setitem := char ● "},
		"setitems": {acType: "Shift", next: "posset := LBRAC setitems ● RBRAC"},
		"setitem": {acType: "Shift", next: "setitems := setitem ● "},
		"range": {acType: "Shift", next: "setitem := range ● "},
	},
	"setitem := char ● ": {
		"CHAR": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"N": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"T": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"R": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"HYPHEN": {acType: "Shift", next: "range := char HYPHEN ● char"},
	},
	"range := char HYPHEN ● char": {
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"char": {acType: "Shift", next: "range := char HYPHEN char ● "},
	},
	"range := char HYPHEN char ● ": {
		"CHAR": {acType: "Reduce", next: "range", reduceBy: 3},
		"NEWLINE": {acType: "Reduce", next: "range", reduceBy: 3},
		"TAB": {acType: "Reduce", next: "range", reduceBy: 3},
		"RETURN": {acType: "Reduce", next: "range", reduceBy: 3},
		"N": {acType: "Reduce", next: "range", reduceBy: 3},
		"T": {acType: "Reduce", next: "range", reduceBy: 3},
		"R": {acType: "Reduce", next: "range", reduceBy: 3},
		"UNDERSCORE": {acType: "Reduce", next: "range", reduceBy: 3},
		"BSLASH": {acType: "Reduce", next: "range", reduceBy: 3},
		"RBRAC": {acType: "Reduce", next: "range", reduceBy: 3},
	},
	"posset := LBRAC setitems ● RBRAC": {
		"RBRAC": {acType: "Shift", next: "posset := LBRAC setitems RBRAC ● "},
	},
	"posset := LBRAC setitems RBRAC ● ": {
		"ALTERNATE": {acType: "Reduce", next: "posset", reduceBy: 3},
		"KLEENE": {acType: "Reduce", next: "posset", reduceBy: 3},
		"PLUS": {acType: "Reduce", next: "posset", reduceBy: 3},
		"QUESTION": {acType: "Reduce", next: "posset", reduceBy: 3},
		"LPAREN": {acType: "Reduce", next: "posset", reduceBy: 3},
		"RPAREN": {acType: "Reduce", next: "posset", reduceBy: 3},
		"WILDCARD": {acType: "Reduce", next: "posset", reduceBy: 3},
		"CHAR": {acType: "Reduce", next: "posset", reduceBy: 3},
		"NEWLINE": {acType: "Reduce", next: "posset", reduceBy: 3},
		"TAB": {acType: "Reduce", next: "posset", reduceBy: 3},
		"RETURN": {acType: "Reduce", next: "posset", reduceBy: 3},
		"N": {acType: "Reduce", next: "posset", reduceBy: 3},
		"T": {acType: "Reduce", next: "posset", reduceBy: 3},
		"R": {acType: "Reduce", next: "posset", reduceBy: 3},
		"UNDERSCORE": {acType: "Reduce", next: "posset", reduceBy: 3},
		"BSLASH": {acType: "Reduce", next: "posset", reduceBy: 3},
		"LBRAC": {acType: "Reduce", next: "posset", reduceBy: 3},
		"\x18": {acType: "Reduce", next: "posset", reduceBy: 3},
	},
	"setitems := setitem ● ": {
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"RBRAC": {acType: "Reduce", next: "setitems", reduceBy: 1},
		"char": {acType: "Shift", next: "setitem := char ● "},
		"setitems": {acType: "Shift", next: "setitems := setitem setitems ● "},
		"setitem": {acType: "Shift", next: "setitems := setitem ● "},
		"range": {acType: "Shift", next: "setitem := range ● "},
	},
	"setitems := setitem setitems ● ": {
		"RBRAC": {acType: "Reduce", next: "setitems", reduceBy: 2},
	},
	"setitem := range ● ": {
		"CHAR": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"N": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"T": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"R": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "setitem", reduceBy: 1},
		"RBRAC": {acType: "Reduce", next: "setitem", reduceBy: 1},
	},
	"negset := LBRAC CARET ● setitems RBRAC": {
		"CHAR": {acType: "Shift", next: "char := CHAR ● "},
		"NEWLINE": {acType: "Shift", next: "char := NEWLINE ● "},
		"TAB": {acType: "Shift", next: "char := TAB ● "},
		"RETURN": {acType: "Shift", next: "char := RETURN ● "},
		"N": {acType: "Shift", next: "char := N ● "},
		"T": {acType: "Shift", next: "char := T ● "},
		"R": {acType: "Shift", next: "char := R ● "},
		"UNDERSCORE": {acType: "Shift", next: "char := UNDERSCORE ● "},
		"BSLASH": {acType: "Shift", next: "char := BSLASH ● LPAREN"},
		"char": {acType: "Shift", next: "setitem := char ● "},
		"setitems": {acType: "Shift", next: "negset := LBRAC CARET setitems ● RBRAC"},
		"setitem": {acType: "Shift", next: "setitems := setitem ● "},
		"range": {acType: "Shift", next: "setitem := range ● "},
	},
	"negset := LBRAC CARET setitems ● RBRAC": {
		"RBRAC": {acType: "Shift", next: "negset := LBRAC CARET setitems RBRAC ● "},
	},
	"negset := LBRAC CARET setitems RBRAC ● ": {
		"ALTERNATE": {acType: "Reduce", next: "negset", reduceBy: 4},
		"KLEENE": {acType: "Reduce", next: "negset", reduceBy: 4},
		"PLUS": {acType: "Reduce", next: "negset", reduceBy: 4},
		"QUESTION": {acType: "Reduce", next: "negset", reduceBy: 4},
		"LPAREN": {acType: "Reduce", next: "negset", reduceBy: 4},
		"RPAREN": {acType: "Reduce", next: "negset", reduceBy: 4},
		"WILDCARD": {acType: "Reduce", next: "negset", reduceBy: 4},
		"CHAR": {acType: "Reduce", next: "negset", reduceBy: 4},
		"NEWLINE": {acType: "Reduce", next: "negset", reduceBy: 4},
		"TAB": {acType: "Reduce", next: "negset", reduceBy: 4},
		"RETURN": {acType: "Reduce", next: "negset", reduceBy: 4},
		"N": {acType: "Reduce", next: "negset", reduceBy: 4},
		"T": {acType: "Reduce", next: "negset", reduceBy: 4},
		"R": {acType: "Reduce", next: "negset", reduceBy: 4},
		"UNDERSCORE": {acType: "Reduce", next: "negset", reduceBy: 4},
		"BSLASH": {acType: "Reduce", next: "negset", reduceBy: 4},
		"LBRAC": {acType: "Reduce", next: "negset", reduceBy: 4},
		"\x18": {acType: "Reduce", next: "negset", reduceBy: 4},
	},
	"simplere := concat ● ": {
		"ALTERNATE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"N": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"T": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"R": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "simplere", reduceBy: 1},
	},
	"simplere := basicre ● ": {
		"ALTERNATE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"LPAREN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"RPAREN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"WILDCARD": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"CHAR": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"NEWLINE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"TAB": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"RETURN": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"N": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"T": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"R": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"UNDERSCORE": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"BSLASH": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"LBRAC": {acType: "Reduce", next: "simplere", reduceBy: 1},
		"\x18": {acType: "Reduce", next: "simplere", reduceBy: 1},
	},
}

var start string = "\x19 :=  ● re \x18"

func action1(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Split{semstack[1], semstack[0]}}, semstack[2:]...)
}

func action2(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Concat{semstack[1], semstack[0]}}, semstack[2:]...)
}

func action3(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Kleene{semstack[0]}}, semstack[1:]...)
}

func action4(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Concat{semstack[0], Kleene(semstack[0])}}, semstack[1:]...)
}

func action5(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Split{semstack[0], nil}}, semstack[1:]...)
}

func action6(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Prim{'.', true}}, semstack...)
}

func action7(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Prim{currentToken, false}}, semstack...)
}

func action8(currentToken []rune, semstack []SemanticType) []SemanticType{
    return append([]Tree{&Prim{currentToken, false}}, semstack...)
}

func action9(currentToken []rune, semstack []SemanticType) []SemanticType{
    n := currentToken
    if currentToken == 'n' {
        n = '\n'
    }
    if currentToken == 't' {
        n = '\t'
    }
    if currentToken == 'r' {
        n = '\r'
    }
    if currentToken == '_' {
        n = ' '
    }
    return append([]Tree{&Prim{n, false}}, semstack...)
}

func action11(currentToken []rune, semstack []SemanticType) []SemanticType{
    var out []rune
    for i := 32; i < 127; i++ {
        flag := false
        for _, v := range semstack[0].chars {
            if rune(i) == v {
                flag = true
                break
            }
        }
        if !flag {
            out = append(out, rune(i))
        }
    }

    flagn, flagt := false, false
    for _, v := range semstack[0].chars {
        if '\n' == v {
            flagn = true
        }
        if '\t' == v {
            flagt = true
        }
        if flagn && flagt {
            break
        }
    }

    if !flagn {
        out = append(out, '\n')
    }

    if !flagt {
        out = append(out, '\t')
    }

    return append([]Tree{&CharSelect{out}}, semstack[1:]...)
}

func action12(currentToken []rune, semstack []SemanticType) []SemanticType{
    ch1 := semstack[1]
    ch2 := semstack[0]
    out := ch1.chars
    for _, v2 := range ch2.chars {
        flag := false
        for _, v1 := range ch1.chars {
            if v1 == v2 {
                flag = true
                break
            }
        }
        if !flag {
            out = append(out, v2)
        }
    }
    return append([]Tree{&CharSelect{out}}, semstack[1:]...)
}

func action13(currentToken []rune, semstack []SemanticType) []SemanticType{
    p := semstack[0].primitive
    return append([]Tree{&CharSelect{[]rune{p}}}, semstack[1:]...)
}

func action14(currentToken []rune, semstack []SemanticType) []SemanticType{
    char1 := semstack[1].primitive
    char2 := semstack[0].primitive
    if int(char1) > int(char2) {
        return append([]Tree{&CharSelect{[]rune{}}}, semstack[2:]...)
    }
    out := []rune{}
    for i := int(char1); i < int(char2) + 1; i++ {
        out = append(out, rune(i))
    }
    return append([]Tree{&CharSelect{out}}, semstack[2:])
}

var actions = map[string]func(l []rune, s []SemanticType) []SemanticType{
	"union := re ALTERNATE simplere ● ": func(l []rune, s []SemanticType) []SemanticType { action1(l, s) },
	"concat := simplere basicre ● ": func(l []rune, s []SemanticType) []SemanticType { action2(l, s) },
	"star := elemre KLEENE ● ": func(l []rune, s []SemanticType) []SemanticType { action3(l, s) },
	"plus := elemre PLUS ● ": func(l []rune, s []SemanticType) []SemanticType { action4(l, s) },
	"question := elemre QUESTION ● ": func(l []rune, s []SemanticType) []SemanticType { action5(l, s) },
	"any := WILDCARD ● ": func(l []rune, s []SemanticType) []SemanticType { action6(l, s) },
	"char := CHAR ● ": func(l []rune, s []SemanticType) []SemanticType { action7(l, s) },
	"char := NEWLINE ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := TAB ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := RETURN ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := N ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := T ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := R ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := UNDERSCORE ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH LPAREN ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH RPAREN ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH LBRAC ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH RBRAC ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH KLEENE ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH PLUS ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH QUESTION ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH CARET ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH HYPHEN ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH WILDCARD ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH ALTERNATE ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH BSLASH ● ": func(l []rune, s []SemanticType) []SemanticType { action8(l, s) },
	"char := BSLASH UNDERSCORE ● ": func(l []rune, s []SemanticType) []SemanticType { action9(l, s) },
	"char := BSLASH N ● ": func(l []rune, s []SemanticType) []SemanticType { action9(l, s) },
	"char := BSLASH T ● ": func(l []rune, s []SemanticType) []SemanticType { action9(l, s) },
	"char := BSLASH R ● ": func(l []rune, s []SemanticType) []SemanticType { action9(l, s) },
	"negset := LBRAC CARET setitems RBRAC ● ": func(l []rune, s []SemanticType) []SemanticType { action11(l, s) },
	"setitems := setitem setitems ● ": func(l []rune, s []SemanticType) []SemanticType { action12(l, s) },
	"setitem := char ● ": func(l []rune, s []SemanticType) []SemanticType { action13(l, s) },
	"range := char HYPHEN char ● ": func(l []rune, s []SemanticType) []SemanticType { action14(l, s) },
}

var LexerParser = Parser{table, start, actions}